[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs

lib_deps =
    m5stack/M5Cardputer@^1.0.0

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
